### ISSUE TITLE
Add build for python 3.8

### ISSUE THREAD

**Issue by sdebionne** [conda-forge/sphinx_rtd_theme-feedstock#19]
Would it be possible to add a build for Python 3.8, being the Python version in the base env of the conda-forge docker image, please?

Edit: I just noticed that `sphinx` is not available neither for `3.8`, so downgrading python for building documentation is probably the best option for now.

**Comment by chohner** [comment]
closing this, as `sphinx_rtd_theme` does support `3.8`
